version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bdd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pip188
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7
    networks:
      - appnet

  web:
    build: .
    command: gunicorn scraper.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=scraper.settings
      - SECRET_KEY=django-insecure-fg1vl0s*akgind9!vb+v4e0&2i3-oyd_th-jp^bc7ntd7osw80
      - DATABASE_URL=postgres://postgres:pip188@db:5432/bdd
    networks:
      - appnet

  celery:
    build: .
    command: celery -A scraper worker --loglevel=info --pool=solo
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=scraper.settings
      - SECRET_KEY=django-insecure-fg1vl0s*akgind9!vb+v4e0&2i3-oyd_th-jp^bc7ntd7osw80
      - DATABASE_URL=postgres://postgres:pip188@db:5432/bdd
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data: